# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tutorials',
                'doc_host': 'https://bilalcodehub.github.io',
                'git_url': 'https://github.com/bilalcodehub/tutorials',
                'lib_path': 'tutorials'},
  'syms': {'tutorials.core': {'tutorials.core.foo': ('core.html#foo', 'tutorials/core.py')}}}
